require 'simplecov'
SimpleCov.start
require 'date'
require 'minitest/autorun'
require 'minitest/pride'
require 'mocha/minitest'
require './lib/enigma'
require './lib/key_shift'
require './lib/offset_shift'
require './lib/encryptor'
